import { SUPPORTED_LOCALES, getPreferredLocale, tForLocale, type AppLocale } from './i18n'
import type { RecordingScope, SessionRecord } from './types'

export function getScopeLabel(scope: RecordingScope, locale: AppLocale = getPreferredLocale()) {
  switch (scope) {
    case 'current-tab':
      return tForLocale(locale, 'scope_current_tab')
    case 'cross-tab':
      return tForLocale(locale, 'scope_cross_tab')
    case 'all-windows':
      return tForLocale(locale, 'scope_all_windows')
    default:
      return scope
  }
}

function formatForName(ts: number) {
  const date = new Date(ts)
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  const hour = String(date.getHours()).padStart(2, '0')
  const minute = String(date.getMinutes()).padStart(2, '0')
  return `${year}-${month}-${day} ${hour}:${minute}`
}

export function buildSessionName(startTime: number, scope: RecordingScope, locale: AppLocale = getPreferredLocale()) {
  return `${getScopeLabel(scope, locale)} ${formatForName(startTime)}`
}

function getLegacyGeneratedLabels(scope: RecordingScope) {
  switch (scope) {
    case 'current-tab':
      return ['?? Tab']
    case 'cross-tab':
      return ['? Tab']
    case 'all-windows':
      return ['????']
    default:
      return []
  }
}

function isAutoGeneratedSessionName(name: string, startTime: number, scope: RecordingScope) {
  const generatedNames = [
    ...SUPPORTED_LOCALES.map((locale) => buildSessionName(startTime, scope, locale)),
    ...getLegacyGeneratedLabels(scope).map((label) => `${label} ${formatForName(startTime)}`),
  ]
  if (generatedNames.includes(name)) {
    return true
  }

  const legacyLabels = getLegacyGeneratedLabels(scope)
  return legacyLabels.some((label) => name.startsWith(label))
}

export function getSessionDisplayName(session: Pick<SessionRecord, 'name' | 'startTime' | 'scope'>) {
  const trimmed = session.name?.trim()
  if (trimmed && !isAutoGeneratedSessionName(trimmed, session.startTime, session.scope)) {
    return trimmed
  }

  return buildSessionName(session.startTime, session.scope)
}
